name: Deploy to GitHub Pages

on:
  # 只要你推送到 main 分支，就会自动触发部署
  push:
    branches: [ main ]
  # 允许你在 GitHub 网页上手动点击按钮触发部署
  workflow_dispatch:

# 设置 GitHub 权限，允许它把文件写入到 Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Install, build, and upload your site
        uses: withastro/action@v3

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4